---
abstract: 'Perl extension for exif library'
author:
  - 'sergey s prozhogin <ccpro@rrelaxo.org.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-EXIF
no_index:
  directory:
    - t
    - inc
requires: {}
version: 2.01
